name: Tools Release
run-name: "Ninja-MAC-None-None-C17-POSIX-POSIX-ARM64-TOOLS_RELEASE"
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/configure__github_runner_image_runtime_mac.yml
    with:
      cmake_command: -VERBOSE -CICD_BUILD -TEIKITU -IDE:NINJA -COMPILER:CLANG -THREAD:POSIX -OS:POSIX -DEVICE:DESKTOP -CPU:C17_A64 -GPU:NONE -BUILD_TYPE:TOOLS_RELEASE
    secrets: inherit
