name: Tools Release
run-name: "Ninja-LNX-None-None-C17-POSIX-POSIX-X64-TOOLS_RELEASE"
on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/configure__github_runner_image_runtime.yml
    with:
        os: ubuntu-24.04
        cmake_command: -VERBOSE -CICD_BUILD -TEIKITU -IDE:NINJA -COMPILER:CLANG -THREAD:POSIX -OS:POSIX -DEVICE:DESKTOP -CPU:C17_X64 -GPU:NONE -BUILD_TYPE:TOOLS_RELEASE
    secrets: inherit
